version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mpp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

  db:
    image: 'postgres:15.2-alpine'
    hostname: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mpp
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/aa_init-db.sql
      - ./dbscripts/execute_sql_script.sh:/spring/execute_sql_script.sh
      - ./dbscripts/insert_user.sql:/docker-entrypoint-initdb.d/ab_insert_user.sql
      - ./dbscripts/insert_user_profile.sql:/docker-entrypoint-initdb.d/ac_insert_user_profile.sql
      - ./dbscripts/insert_distributor.sql:/docker-entrypoint-initdb.d/ad_insert_distributor.sql
      - ./dbscripts/insert_shipment.sql:/docker-entrypoint-initdb.d/ae_insert_shipment.sql
      - ./dbscripts/insert_car_model.sql:/docker-entrypoint-initdb.d/af_insert_car_model.sql
      - ./dbscripts/insert_customer.sql:/docker-entrypoint-initdb.d/ag_insert_customer.sql
      - ./dbscripts/insert_purchase.sql:/docker-entrypoint-initdb.d/ah_insert_purchase.sql
#      - ./dbscripts/insert_cars_on_purchase.sql:/docker-entrypoint-initdb.d/ai_insert_cars_on_purchase.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/sdi-2023-car-dealership.crabdance.com/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/sdi-2023-car-dealership.crabdance.com/privkey.pem:/etc/nginx/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
